adds wire between co2 api

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -1,47 +1,50 @@
-FROM node:16-slim AS deps
-RUN apt-get update
-RUN apt-get install -y openssl
-WORKDIR /app
-COPY package.json yarn.lock ./
-COPY prisma ./prisma/ 
-RUN yarn install --frozen-lockfile
-
-# Rebuild the source code only when needed
-FROM node:16-slim AS builder
+# 1. Install dependencies only when needed
+FROM node:16-alpine AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 
 WORKDIR /app
-COPY . .
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+COPY ./prisma ./prisma
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+# 2. Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
-RUN yarn build && yarn install --production --ignore-scripts --prefer-offline
+COPY . .
+# This will do the trick, use the corresponding env file for each environment.
+COPY .env .env
+RUN yarn build
 
-# Production image, copy all the files and run next
-FROM node:16-slim AS runner
+# 3. Production image, copy all the files and run next
+FROM node:16-alpine AS runner
 WORKDIR /app
-RUN pwd
 
-ENV NODE_ENV production
+ENV NODE_ENV=production
 
-RUN groupadd -r nodejs -g 1001
-RUN useradd -r nextjs -g 1001
-RUN ls
+RUN addgroup -g 1001 -S nodejs
+RUN adduser -S nextjs -u 1001
 
-# You only need to copy next.config.js if you are NOT using the default configuration
-COPY --from=builder /app/next.config.mjs ./next.config.mjs
 COPY --from=builder /app/public ./public
-COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
-COPY --from=builder /app/node_modules ./node_modules
-COPY --from=builder /app/package.json ./package.json
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
 
 USER nextjs
 
-ENV PORT=80
-EXPOSE 80
+EXPOSE 3000
 
-# Next.js collects completely anonymous telemetry data about general usage.
-# Learn more here: https://nextjs.org/telemetry
-# Uncomment the following line in case you want to disable telemetry.
-ENV NEXT_TELEMETRY_DISABLED 1
+ENV PORT 3000
 
-RUN ls
-
-CMD ["yarn", "start"]
+CMD ["node", "server.js"]
